[env:lolin_d32]
platform = espressif32
board = lolin_d32
framework = arduino

; micro-ROS transport via USB Serial
board_microros_transport = serial

; micro-ROS für Jazzy
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio

; micro-ROS braucht mehr Flash als default
board_build.partitions = huge_app.csv

; Serial Monitor
monitor_speed = 115200
